# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QFrame, QGraphicsView,
    QHBoxLayout, QHeaderView, QLabel, QListView,
    QListWidget, QListWidgetItem, QPlainTextEdit, QPushButton,
    QSizePolicy, QSlider, QSpacerItem, QSplitter,
    QStackedWidget, QTreeWidget, QTreeWidgetItem, QVBoxLayout,
    QWidget)
import resources_rc

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1148, 861)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QSize(640, 480))
        self.verticalLayout_4 = QVBoxLayout(Form)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.change_page = QStackedWidget(Form)
        self.change_page.setObjectName(u"change_page")
        self.change_page.setMaximumSize(QSize(16777215, 16777215))
        self.edit_stage_frame = QWidget()
        self.edit_stage_frame.setObjectName(u"edit_stage_frame")
        self.verticalLayout_19 = QVBoxLayout(self.edit_stage_frame)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName(u"verticalLayout_19")
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.menu_frame = QFrame(self.edit_stage_frame)
        self.menu_frame.setObjectName(u"menu_frame")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.menu_frame.sizePolicy().hasHeightForWidth())
        self.menu_frame.setSizePolicy(sizePolicy1)
        self.menu_frame.setMinimumSize(QSize(0, 40))
        self.menu_frame.setMaximumSize(QSize(16777215, 40))
        self.menu_frame.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.menu_frame.setStyleSheet(u"")
        self.menu_frame.setFrameShape(QFrame.Shape.NoFrame)
        self.menu_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.menu_frame.setLineWidth(0)
        self.horizontalLayout_3 = QHBoxLayout(self.menu_frame)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 5, 0)
        self.btn_logo = QPushButton(self.menu_frame)
        self.btn_logo.setObjectName(u"btn_logo")
        self.btn_logo.setEnabled(True)
        sizePolicy.setHeightForWidth(self.btn_logo.sizePolicy().hasHeightForWidth())
        self.btn_logo.setSizePolicy(sizePolicy)
        self.btn_logo.setMinimumSize(QSize(60, 39))
        self.btn_logo.setMaximumSize(QSize(60, 39))
        self.btn_logo.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        icon = QIcon()
        icon.addFile(u":/icons/logo.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_logo.setIcon(icon)
        self.btn_logo.setIconSize(QSize(90, 40))
        self.btn_logo.setFlat(False)

        self.horizontalLayout_3.addWidget(self.btn_logo, 0, Qt.AlignmentFlag.AlignTop)

        self.btn_file = QPushButton(self.menu_frame)
        self.btn_file.setObjectName(u"btn_file")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.btn_file.sizePolicy().hasHeightForWidth())
        self.btn_file.setSizePolicy(sizePolicy2)
        self.btn_file.setMinimumSize(QSize(0, 0))
        self.btn_file.setMaximumSize(QSize(16777215, 40))
        icon1 = QIcon()
        icon1.addFile(u":/icons/icon--file.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_file.setIcon(icon1)
        self.btn_file.setIconSize(QSize(18, 18))

        self.horizontalLayout_3.addWidget(self.btn_file)

        self.btn_code_editor = QPushButton(self.menu_frame)
        self.btn_code_editor.setObjectName(u"btn_code_editor")
        sizePolicy2.setHeightForWidth(self.btn_code_editor.sizePolicy().hasHeightForWidth())
        self.btn_code_editor.setSizePolicy(sizePolicy2)
        self.btn_code_editor.setMinimumSize(QSize(0, 0))
        self.btn_code_editor.setMaximumSize(QSize(16777215, 40))
        icon2 = QIcon()
        icon2.addFile(u":/icons/icon--edit.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_code_editor.setIcon(icon2)
        self.btn_code_editor.setIconSize(QSize(24, 24))

        self.horizontalLayout_3.addWidget(self.btn_code_editor)

        self.btn_sprite_editor = QPushButton(self.menu_frame)
        self.btn_sprite_editor.setObjectName(u"btn_sprite_editor")
        sizePolicy2.setHeightForWidth(self.btn_sprite_editor.sizePolicy().hasHeightForWidth())
        self.btn_sprite_editor.setSizePolicy(sizePolicy2)
        self.btn_sprite_editor.setMinimumSize(QSize(0, 0))
        self.btn_sprite_editor.setMaximumSize(QSize(16777215, 40))
        icon3 = QIcon()
        icon3.addFile(u":/icons/addons.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_sprite_editor.setIcon(icon3)
        self.btn_sprite_editor.setIconSize(QSize(20, 20))

        self.horizontalLayout_3.addWidget(self.btn_sprite_editor)

        self.btn_setting = QPushButton(self.menu_frame)
        self.btn_setting.setObjectName(u"btn_setting")
        sizePolicy2.setHeightForWidth(self.btn_setting.sizePolicy().hasHeightForWidth())
        self.btn_setting.setSizePolicy(sizePolicy2)
        self.btn_setting.setMinimumSize(QSize(0, 0))
        self.btn_setting.setMaximumSize(QSize(16777215, 40))
        icon4 = QIcon()
        icon4.addFile(u":/icons/icon--settings.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_setting.setIcon(icon4)
        self.btn_setting.setIconSize(QSize(22, 22))

        self.horizontalLayout_3.addWidget(self.btn_setting)

        self.btn_save = QPushButton(self.menu_frame)
        self.btn_save.setObjectName(u"btn_save")
        sizePolicy2.setHeightForWidth(self.btn_save.sizePolicy().hasHeightForWidth())
        self.btn_save.setSizePolicy(sizePolicy2)
        self.btn_save.setMinimumSize(QSize(0, 0))
        self.btn_save.setMaximumSize(QSize(80, 40))
        icon5 = QIcon()
        icon5.addFile(u":/icons/\u4fdd\u5b58.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_save.setIcon(icon5)
        self.btn_save.setIconSize(QSize(16, 16))

        self.horizontalLayout_3.addWidget(self.btn_save)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_2)

        self.btn_help = QPushButton(self.menu_frame)
        self.btn_help.setObjectName(u"btn_help")
        icon6 = QIcon()
        icon6.addFile(u":/icons/help.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_help.setIcon(icon6)
        self.btn_help.setIconSize(QSize(24, 24))

        self.horizontalLayout_3.addWidget(self.btn_help)

        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 1)
        self.horizontalLayout_3.setStretch(4, 1)
        self.horizontalLayout_3.setStretch(5, 1)
        self.horizontalLayout_3.setStretch(6, 6)

        self.verticalLayout_19.addWidget(self.menu_frame)

        self.editor_stacked = QStackedWidget(self.edit_stage_frame)
        self.editor_stacked.setObjectName(u"editor_stacked")
        self.editor_code_web = QWidget()
        self.editor_code_web.setObjectName(u"editor_code_web")
        self.verticalLayout_5 = QVBoxLayout(self.editor_code_web)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.editor_code_web)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.frame.setLineWidth(0)
        self.horizontalLayout_2 = QHBoxLayout(self.frame)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.sidebar_frame = QFrame(self.frame)
        self.sidebar_frame.setObjectName(u"sidebar_frame")
        sizePolicy.setHeightForWidth(self.sidebar_frame.sizePolicy().hasHeightForWidth())
        self.sidebar_frame.setSizePolicy(sizePolicy)
        self.sidebar_frame.setMinimumSize(QSize(340, 0))
        self.sidebar_frame.setMaximumSize(QSize(340, 16777215))
        self.sidebar_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.sidebar_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.sidebar_frame)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(8, 0, 0, 0)
        self.screen_btn_frame = QFrame(self.sidebar_frame)
        self.screen_btn_frame.setObjectName(u"screen_btn_frame")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.screen_btn_frame.sizePolicy().hasHeightForWidth())
        self.screen_btn_frame.setSizePolicy(sizePolicy3)
        self.screen_btn_frame.setMinimumSize(QSize(324, 0))
        self.screen_btn_frame.setMaximumSize(QSize(324, 30))
        self.screen_btn_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.screen_btn_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.screen_btn_frame)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(5, 0, 5, 0)
        self.btn_run = QPushButton(self.screen_btn_frame)
        self.btn_run.setObjectName(u"btn_run")
        self.btn_run.setMinimumSize(QSize(24, 24))
        self.btn_run.setMaximumSize(QSize(24, 24))
        icon7 = QIcon()
        icon7.addFile(u":/icons/icon--play.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_run.setIcon(icon7)
        self.btn_run.setCheckable(True)

        self.horizontalLayout_5.addWidget(self.btn_run)

        self.btn_stop = QPushButton(self.screen_btn_frame)
        self.btn_stop.setObjectName(u"btn_stop")
        self.btn_stop.setMinimumSize(QSize(24, 24))
        self.btn_stop.setMaximumSize(QSize(24, 24))
        icon8 = QIcon()
        icon8.addFile(u":/icons/icon--stop-all.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_stop.setIcon(icon8)
        self.btn_stop.setCheckable(False)
        self.btn_stop.setAutoExclusive(True)

        self.horizontalLayout_5.addWidget(self.btn_stop)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_5.addItem(self.horizontalSpacer_3)

        self.btn_full_screen = QPushButton(self.screen_btn_frame)
        self.btn_full_screen.setObjectName(u"btn_full_screen")
        self.btn_full_screen.setMinimumSize(QSize(24, 24))
        self.btn_full_screen.setMaximumSize(QSize(24, 24))
        icon9 = QIcon()
        icon9.addFile(u":/icons/icon--fullscreen.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_full_screen.setIcon(icon9)
        self.btn_full_screen.setIconSize(QSize(20, 20))
        self.btn_full_screen.setAutoExclusive(False)

        self.horizontalLayout_5.addWidget(self.btn_full_screen)

        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 4)
        self.horizontalLayout_5.setStretch(3, 1)

        self.verticalLayout_2.addWidget(self.screen_btn_frame)

        self.edit_stage_container = QFrame(self.sidebar_frame)
        self.edit_stage_container.setObjectName(u"edit_stage_container")
        sizePolicy.setHeightForWidth(self.edit_stage_container.sizePolicy().hasHeightForWidth())
        self.edit_stage_container.setSizePolicy(sizePolicy)
        self.edit_stage_container.setMinimumSize(QSize(324, 244))
        self.edit_stage_container.setMaximumSize(QSize(324, 244))
        self.edit_stage_container.setFrameShape(QFrame.Shape.StyledPanel)
        self.edit_stage_container.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_10 = QVBoxLayout(self.edit_stage_container)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.game_view = QGraphicsView(self.edit_stage_container)
        self.game_view.setObjectName(u"game_view")
        sizePolicy.setHeightForWidth(self.game_view.sizePolicy().hasHeightForWidth())
        self.game_view.setSizePolicy(sizePolicy)
        self.game_view.setMinimumSize(QSize(320, 240))
        self.game_view.setMaximumSize(QSize(320, 240))
        self.game_view.setStyleSheet(u"")
        self.game_view.setFrameShape(QFrame.Shape.Panel)
        self.game_view.setFrameShadow(QFrame.Shadow.Plain)
        self.game_view.setLineWidth(0)
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.BrushStyle.NoBrush)
        self.game_view.setBackgroundBrush(brush)
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.BrushStyle.NoBrush)
        self.game_view.setForegroundBrush(brush1)

        self.verticalLayout_10.addWidget(self.game_view)


        self.verticalLayout_2.addWidget(self.edit_stage_container)

        self.outline_menu_frame = QFrame(self.sidebar_frame)
        self.outline_menu_frame.setObjectName(u"outline_menu_frame")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.outline_menu_frame.sizePolicy().hasHeightForWidth())
        self.outline_menu_frame.setSizePolicy(sizePolicy4)
        self.outline_menu_frame.setMinimumSize(QSize(324, 50))
        self.outline_menu_frame.setMaximumSize(QSize(324, 16777215))
        self.outline_menu_frame.setStyleSheet(u"")
        self.horizontalLayout_4 = QHBoxLayout(self.outline_menu_frame)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.btn_outline_sprite = QPushButton(self.outline_menu_frame)
        self.btn_outline_sprite.setObjectName(u"btn_outline_sprite")
        self.btn_outline_sprite.setCheckable(True)
        self.btn_outline_sprite.setChecked(True)
        self.btn_outline_sprite.setAutoExclusive(True)
        self.btn_outline_sprite.setAutoDefault(False)
        self.btn_outline_sprite.setFlat(False)

        self.horizontalLayout_4.addWidget(self.btn_outline_sprite)

        self.btn_outline_bg = QPushButton(self.outline_menu_frame)
        self.btn_outline_bg.setObjectName(u"btn_outline_bg")
        self.btn_outline_bg.setCheckable(True)
        self.btn_outline_bg.setAutoExclusive(True)

        self.horizontalLayout_4.addWidget(self.btn_outline_bg)

        self.btn_outline_sound = QPushButton(self.outline_menu_frame)
        self.btn_outline_sound.setObjectName(u"btn_outline_sound")
        self.btn_outline_sound.setCheckable(True)
        self.btn_outline_sound.setAutoExclusive(True)
        self.btn_outline_sound.setAutoDefault(False)
        self.btn_outline_sound.setFlat(False)

        self.horizontalLayout_4.addWidget(self.btn_outline_sound)

        self.btn_outline_code = QPushButton(self.outline_menu_frame)
        self.btn_outline_code.setObjectName(u"btn_outline_code")
        self.btn_outline_code.setCheckable(True)
        self.btn_outline_code.setChecked(False)
        self.btn_outline_code.setAutoExclusive(True)
        self.btn_outline_code.setAutoDefault(False)
        self.btn_outline_code.setFlat(False)

        self.horizontalLayout_4.addWidget(self.btn_outline_code)


        self.verticalLayout_2.addWidget(self.outline_menu_frame)

        self.outline_frame = QFrame(self.sidebar_frame)
        self.outline_frame.setObjectName(u"outline_frame")
        self.outline_frame.setMinimumSize(QSize(324, 0))
        self.outline_frame.setMaximumSize(QSize(324, 16777215))
        self.outline_frame.setStyleSheet(u"")
        self.outline_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.outline_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_6 = QVBoxLayout(self.outline_frame)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.outline_stracked = QStackedWidget(self.outline_frame)
        self.outline_stracked.setObjectName(u"outline_stracked")
        self.outline_stracked.setMinimumSize(QSize(324, 0))
        self.outline_stracked.setMaximumSize(QSize(324, 16777215))
        self.outline_stracked.setStyleSheet(u"")
        self.page_sprite = QWidget()
        self.page_sprite.setObjectName(u"page_sprite")
        self.verticalLayout_12 = QVBoxLayout(self.page_sprite)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.sprite_page_frame = QFrame(self.page_sprite)
        self.sprite_page_frame.setObjectName(u"sprite_page_frame")
        self.sprite_page_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.sprite_page_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_15 = QVBoxLayout(self.sprite_page_frame)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName(u"verticalLayout_15")
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.list_sprite = QListWidget(self.sprite_page_frame)
        self.list_sprite.setObjectName(u"list_sprite")
        self.list_sprite.setIconSize(QSize(80, 80))
        self.list_sprite.setMovement(QListView.Movement.Static)
        self.list_sprite.setResizeMode(QListView.ResizeMode.Adjust)
        self.list_sprite.setSpacing(10)
        self.list_sprite.setViewMode(QListView.ViewMode.IconMode)

        self.verticalLayout_15.addWidget(self.list_sprite)


        self.verticalLayout_12.addWidget(self.sprite_page_frame)

        self.outline_stracked.addWidget(self.page_sprite)
        self.page_map = QWidget()
        self.page_map.setObjectName(u"page_map")
        self.verticalLayout_13 = QVBoxLayout(self.page_map)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.map_page_frame = QFrame(self.page_map)
        self.map_page_frame.setObjectName(u"map_page_frame")
        self.map_page_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.map_page_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.label_3 = QLabel(self.map_page_frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 40, 58, 16))

        self.verticalLayout_13.addWidget(self.map_page_frame)

        self.outline_stracked.addWidget(self.page_map)
        self.page_sound = QWidget()
        self.page_sound.setObjectName(u"page_sound")
        self.verticalLayout_14 = QVBoxLayout(self.page_sound)
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")
        self.sound_page_frame = QFrame(self.page_sound)
        self.sound_page_frame.setObjectName(u"sound_page_frame")
        self.sound_page_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.sound_page_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.label_4 = QLabel(self.sound_page_frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 30, 58, 16))

        self.verticalLayout_14.addWidget(self.sound_page_frame)

        self.outline_stracked.addWidget(self.page_sound)
        self.page_code = QWidget()
        self.page_code.setObjectName(u"page_code")
        self.verticalLayout_9 = QVBoxLayout(self.page_code)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.code_page_frame = QFrame(self.page_code)
        self.code_page_frame.setObjectName(u"code_page_frame")
        self.code_page_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.code_page_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_16 = QVBoxLayout(self.code_page_frame)
        self.verticalLayout_16.setObjectName(u"verticalLayout_16")
        self.verticalLayout_16.setContentsMargins(4, 4, 4, 4)
        self.list_code = QListWidget(self.code_page_frame)
        self.list_code.setObjectName(u"list_code")

        self.verticalLayout_16.addWidget(self.list_code)


        self.verticalLayout_9.addWidget(self.code_page_frame)

        self.outline_stracked.addWidget(self.page_code)

        self.verticalLayout_6.addWidget(self.outline_stracked)


        self.verticalLayout_2.addWidget(self.outline_frame)


        self.horizontalLayout_2.addWidget(self.sidebar_frame)

        self.editor_frame = QFrame(self.frame)
        self.editor_frame.setObjectName(u"editor_frame")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Ignored)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.editor_frame.sizePolicy().hasHeightForWidth())
        self.editor_frame.setSizePolicy(sizePolicy5)
        self.editor_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.editor_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.editor_frame)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.toolbar_frame = QFrame(self.editor_frame)
        self.toolbar_frame.setObjectName(u"toolbar_frame")
        sizePolicy3.setHeightForWidth(self.toolbar_frame.sizePolicy().hasHeightForWidth())
        self.toolbar_frame.setSizePolicy(sizePolicy3)
        self.toolbar_frame.setMinimumSize(QSize(0, 30))
        self.toolbar_frame.setMaximumSize(QSize(16777215, 30))
        self.toolbar_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.toolbar_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout = QHBoxLayout(self.toolbar_frame)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.tab_frame = QFrame(self.toolbar_frame)
        self.tab_frame.setObjectName(u"tab_frame")
        sizePolicy3.setHeightForWidth(self.tab_frame.sizePolicy().hasHeightForWidth())
        self.tab_frame.setSizePolicy(sizePolicy3)
        self.tab_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.tab_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.tab_frame.setLineWidth(0)
        self.horizontalLayout_6 = QHBoxLayout(self.tab_frame)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.tab = QFrame(self.tab_frame)
        self.tab.setObjectName(u"tab")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy6)
        self.tab.setMinimumSize(QSize(0, 30))
        self.tab.setStyleSheet(u"")
        self.tab.setFrameShape(QFrame.Shape.NoFrame)
        self.tab.setFrameShadow(QFrame.Shadow.Raised)
        self.tab.setLineWidth(0)
        self.horizontalLayout_7 = QHBoxLayout(self.tab)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)

        self.horizontalLayout_6.addWidget(self.tab, 0, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.btn_add_tab = QPushButton(self.tab_frame)
        self.btn_add_tab.setObjectName(u"btn_add_tab")
        sizePolicy7 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.btn_add_tab.sizePolicy().hasHeightForWidth())
        self.btn_add_tab.setSizePolicy(sizePolicy7)
        self.btn_add_tab.setMinimumSize(QSize(24, 24))
        self.btn_add_tab.setMaximumSize(QSize(24, 24))
        self.btn_add_tab.setFlat(True)

        self.horizontalLayout_6.addWidget(self.btn_add_tab)


        self.horizontalLayout.addWidget(self.tab_frame, 0, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignBottom)

        self.horizontalLayout.setStretch(0, 1)

        self.verticalLayout_3.addWidget(self.toolbar_frame)

        self.code_frame = QFrame(self.editor_frame)
        self.code_frame.setObjectName(u"code_frame")
        sizePolicy8 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy8.setHorizontalStretch(0)
        sizePolicy8.setVerticalStretch(0)
        sizePolicy8.setHeightForWidth(self.code_frame.sizePolicy().hasHeightForWidth())
        self.code_frame.setSizePolicy(sizePolicy8)
        self.code_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.code_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout = QVBoxLayout(self.code_frame)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(8, 0, 8, 0)
        self.splitter = QSplitter(self.code_frame)
        self.splitter.setObjectName(u"splitter")
        sizePolicy8.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy8)
        self.splitter.setOrientation(Qt.Orientation.Vertical)
        self.code_stacked = QStackedWidget(self.splitter)
        self.code_stacked.setObjectName(u"code_stacked")
        sizePolicy8.setHeightForWidth(self.code_stacked.sizePolicy().hasHeightForWidth())
        self.code_stacked.setSizePolicy(sizePolicy8)
        self.code_stacked.setMinimumSize(QSize(0, 0))
        self.splitter.addWidget(self.code_stacked)
        self.console_output = QPlainTextEdit(self.splitter)
        self.console_output.setObjectName(u"console_output")
        self.console_output.setMaximumSize(QSize(16777215, 16777215))
        self.console_output.setFrameShape(QFrame.Shape.Box)
        self.splitter.addWidget(self.console_output)

        self.verticalLayout.addWidget(self.splitter)


        self.verticalLayout_3.addWidget(self.code_frame)


        self.horizontalLayout_2.addWidget(self.editor_frame)


        self.verticalLayout_5.addWidget(self.frame)

        self.editor_stacked.addWidget(self.editor_code_web)
        self.editor_sprite_web = QWidget()
        self.editor_sprite_web.setObjectName(u"editor_sprite_web")
        self.verticalLayout_18 = QVBoxLayout(self.editor_sprite_web)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName(u"verticalLayout_18")
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.widget_2 = QWidget(self.editor_sprite_web)
        self.widget_2.setObjectName(u"widget_2")
        self.horizontalLayout_11 = QHBoxLayout(self.widget_2)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.sprite_fps_list = QListWidget(self.widget_2)
        self.sprite_fps_list.setObjectName(u"sprite_fps_list")
        self.sprite_fps_list.setMinimumSize(QSize(100, 0))
        self.sprite_fps_list.setMaximumSize(QSize(100, 16777215))
        self.sprite_fps_list.setStyleSheet(u"")
        self.sprite_fps_list.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.sprite_fps_list.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.sprite_fps_list.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self.sprite_fps_list.setMovement(QListView.Movement.Static)
        self.sprite_fps_list.setResizeMode(QListView.ResizeMode.Adjust)
        self.sprite_fps_list.setSpacing(5)
        self.sprite_fps_list.setViewMode(QListView.ViewMode.IconMode)

        self.horizontalLayout_11.addWidget(self.sprite_fps_list)

        self.sprite_canvas = QGraphicsView(self.widget_2)
        self.sprite_canvas.setObjectName(u"sprite_canvas")
        self.sprite_canvas.setStyleSheet(u"")
        self.sprite_canvas.setFrameShape(QFrame.Shape.NoFrame)
        self.sprite_canvas.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.sprite_canvas.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)

        self.horizontalLayout_11.addWidget(self.sprite_canvas)

        self.editor_preview_panel = QWidget(self.widget_2)
        self.editor_preview_panel.setObjectName(u"editor_preview_panel")
        self.editor_preview_panel.setMinimumSize(QSize(264, 0))
        self.editor_preview_panel.setMaximumSize(QSize(264, 16777215))
        self.verticalLayout_20 = QVBoxLayout(self.editor_preview_panel)
        self.verticalLayout_20.setSpacing(1)
        self.verticalLayout_20.setObjectName(u"verticalLayout_20")
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.animate_label = QLabel(self.editor_preview_panel)
        self.animate_label.setObjectName(u"animate_label")
        self.animate_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_20.addWidget(self.animate_label)

        self.preview_bg = QFrame(self.editor_preview_panel)
        self.preview_bg.setObjectName(u"preview_bg")
        self.preview_bg.setMinimumSize(QSize(256, 256))
        self.preview_bg.setMaximumSize(QSize(256, 256))
        self.preview_bg.setFrameShape(QFrame.Shape.NoFrame)
        self.preview_bg.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_17 = QVBoxLayout(self.preview_bg)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName(u"verticalLayout_17")
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.animate_preview = QLabel(self.preview_bg)
        self.animate_preview.setObjectName(u"animate_preview")
        self.animate_preview.setMinimumSize(QSize(256, 256))
        self.animate_preview.setMaximumSize(QSize(256, 256))
        self.animate_preview.setStyleSheet(u"")
        self.animate_preview.setFrameShape(QFrame.Shape.StyledPanel)
        self.animate_preview.setScaledContents(False)
        self.animate_preview.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_17.addWidget(self.animate_preview, 0, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignTop)

        self.fps_slider_box = QHBoxLayout()
        self.fps_slider_box.setObjectName(u"fps_slider_box")
        self.fps_slider_box.setContentsMargins(-1, -1, -1, 4)
        self.horizontalSpacer_6 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.fps_slider_box.addItem(self.horizontalSpacer_6)

        self.fps_slider = QSlider(self.preview_bg)
        self.fps_slider.setObjectName(u"fps_slider")
        self.fps_slider.setStyleSheet(u"")
        self.fps_slider.setOrientation(Qt.Orientation.Horizontal)

        self.fps_slider_box.addWidget(self.fps_slider)

        self.horizontalSpacer_7 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.fps_slider_box.addItem(self.horizontalSpacer_7)

        self.fps_slider_box.setStretch(0, 1)
        self.fps_slider_box.setStretch(1, 2)
        self.fps_slider_box.setStretch(2, 1)

        self.verticalLayout_17.addLayout(self.fps_slider_box)


        self.verticalLayout_20.addWidget(self.preview_bg, 0, Qt.AlignmentFlag.AlignHCenter)

        self.btn_preview_btns = QFrame(self.editor_preview_panel)
        self.btn_preview_btns.setObjectName(u"btn_preview_btns")
        self.btn_preview_btns.setFrameShape(QFrame.Shape.StyledPanel)
        self.btn_preview_btns.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_8 = QHBoxLayout(self.btn_preview_btns)
        self.horizontalLayout_8.setSpacing(4)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(8, 8, 8, 8)
        self.btn_preview_prev = QPushButton(self.btn_preview_btns)
        self.btn_preview_prev.setObjectName(u"btn_preview_prev")
        self.btn_preview_prev.setMinimumSize(QSize(38, 24))
        self.btn_preview_prev.setMaximumSize(QSize(38, 24))
        icon10 = QIcon()
        icon10.addFile(u":/icons/btn_preview_prev.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_preview_prev.setIcon(icon10)
        self.btn_preview_prev.setIconSize(QSize(28, 16))
        self.btn_preview_prev.setFlat(True)

        self.horizontalLayout_8.addWidget(self.btn_preview_prev)

        self.btn_preview_play = QPushButton(self.btn_preview_btns)
        self.btn_preview_play.setObjectName(u"btn_preview_play")
        self.btn_preview_play.setMinimumSize(QSize(38, 24))
        self.btn_preview_play.setMaximumSize(QSize(38, 24))
        icon11 = QIcon()
        icon11.addFile(u":/icons/btn_preview_play.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon11.addFile(u":/icons/btn_preview_pause.svg", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.btn_preview_play.setIcon(icon11)
        self.btn_preview_play.setIconSize(QSize(28, 16))
        self.btn_preview_play.setCheckable(True)
        self.btn_preview_play.setFlat(True)

        self.horizontalLayout_8.addWidget(self.btn_preview_play)

        self.btn_preview_next = QPushButton(self.btn_preview_btns)
        self.btn_preview_next.setObjectName(u"btn_preview_next")
        self.btn_preview_next.setMinimumSize(QSize(38, 24))
        self.btn_preview_next.setMaximumSize(QSize(38, 24))
        icon12 = QIcon()
        icon12.addFile(u":/icons/btn_preview_next.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_preview_next.setIcon(icon12)
        self.btn_preview_next.setIconSize(QSize(28, 16))
        self.btn_preview_next.setFlat(True)

        self.horizontalLayout_8.addWidget(self.btn_preview_next)

        self.btn_preview_scale = QPushButton(self.btn_preview_btns)
        self.btn_preview_scale.setObjectName(u"btn_preview_scale")
        self.btn_preview_scale.setMinimumSize(QSize(38, 24))
        self.btn_preview_scale.setMaximumSize(QSize(38, 24))
        icon13 = QIcon()
        icon13.addFile(u":/icons/btn_preview_scale.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_preview_scale.setIcon(icon13)
        self.btn_preview_scale.setIconSize(QSize(28, 16))
        self.btn_preview_scale.setFlat(True)

        self.horizontalLayout_8.addWidget(self.btn_preview_scale)

        self.btn_preview_change_bg = QPushButton(self.btn_preview_btns)
        self.btn_preview_change_bg.setObjectName(u"btn_preview_change_bg")
        self.btn_preview_change_bg.setMinimumSize(QSize(38, 24))
        self.btn_preview_change_bg.setMaximumSize(QSize(38, 24))
        icon14 = QIcon()
        icon14.addFile(u":/icons/btn_preview_change_bg.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_preview_change_bg.setIcon(icon14)
        self.btn_preview_change_bg.setIconSize(QSize(28, 16))
        self.btn_preview_change_bg.setFlat(True)

        self.horizontalLayout_8.addWidget(self.btn_preview_change_bg)

        self.btn_preview_add = QPushButton(self.btn_preview_btns)
        self.btn_preview_add.setObjectName(u"btn_preview_add")
        self.btn_preview_add.setMinimumSize(QSize(38, 24))
        self.btn_preview_add.setMaximumSize(QSize(38, 24))
        icon15 = QIcon()
        icon15.addFile(u":/icons/btn_preview_add.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_preview_add.setIcon(icon15)
        self.btn_preview_add.setIconSize(QSize(28, 16))
        self.btn_preview_add.setFlat(True)

        self.horizontalLayout_8.addWidget(self.btn_preview_add)


        self.verticalLayout_20.addWidget(self.btn_preview_btns, 0, Qt.AlignmentFlag.AlignHCenter)

        self.animate_list = QTreeWidget(self.editor_preview_panel)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(0, u"1");
        self.animate_list.setHeaderItem(__qtreewidgetitem)
        self.animate_list.setObjectName(u"animate_list")
        self.animate_list.setMinimumSize(QSize(256, 0))
        self.animate_list.setMaximumSize(QSize(256, 16777215))
        self.animate_list.setStyleSheet(u"")
        self.animate_list.setFrameShape(QFrame.Shape.NoFrame)
        self.animate_list.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.animate_list.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.animate_list.header().setVisible(False)

        self.verticalLayout_20.addWidget(self.animate_list, 0, Qt.AlignmentFlag.AlignHCenter)


        self.horizontalLayout_11.addWidget(self.editor_preview_panel)


        self.verticalLayout_18.addWidget(self.widget_2)

        self.editor_stacked.addWidget(self.editor_sprite_web)

        self.verticalLayout_19.addWidget(self.editor_stacked)

        self.change_page.addWidget(self.edit_stage_frame)
        self.fullscreen = QWidget()
        self.fullscreen.setObjectName(u"fullscreen")
        sizePolicy4.setHeightForWidth(self.fullscreen.sizePolicy().hasHeightForWidth())
        self.fullscreen.setSizePolicy(sizePolicy4)
        self.fullscreen.setMinimumSize(QSize(0, 0))
        self.verticalLayout_8 = QVBoxLayout(self.fullscreen)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.bg_layout = QFrame(self.fullscreen)
        self.bg_layout.setObjectName(u"bg_layout")
        sizePolicy9 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy9.setHorizontalStretch(0)
        sizePolicy9.setVerticalStretch(0)
        sizePolicy9.setHeightForWidth(self.bg_layout.sizePolicy().hasHeightForWidth())
        self.bg_layout.setSizePolicy(sizePolicy9)
        self.bg_layout.setStyleSheet(u"")
        self.bg_layout.setFrameShape(QFrame.Shape.StyledPanel)
        self.bg_layout.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_10 = QHBoxLayout(self.bg_layout)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_4 = QSpacerItem(40, 0, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_10.addItem(self.horizontalSpacer_4)

        self.central_stage_wrapper = QFrame(self.bg_layout)
        self.central_stage_wrapper.setObjectName(u"central_stage_wrapper")
        sizePolicy10 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum)
        sizePolicy10.setHorizontalStretch(0)
        sizePolicy10.setVerticalStretch(0)
        sizePolicy10.setHeightForWidth(self.central_stage_wrapper.sizePolicy().hasHeightForWidth())
        self.central_stage_wrapper.setSizePolicy(sizePolicy10)
        self.central_stage_wrapper.setStyleSheet(u"")
        self.central_stage_wrapper.setFrameShape(QFrame.Shape.StyledPanel)
        self.central_stage_wrapper.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_11 = QVBoxLayout(self.central_stage_wrapper)
        self.verticalLayout_11.setSpacing(4)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.fullscreen_tool_bar = QFrame(self.central_stage_wrapper)
        self.fullscreen_tool_bar.setObjectName(u"fullscreen_tool_bar")
        sizePolicy3.setHeightForWidth(self.fullscreen_tool_bar.sizePolicy().hasHeightForWidth())
        self.fullscreen_tool_bar.setSizePolicy(sizePolicy3)
        self.fullscreen_tool_bar.setMinimumSize(QSize(0, 30))
        self.fullscreen_tool_bar.setMaximumSize(QSize(16777215, 30))
        self.fullscreen_tool_bar.setFrameShape(QFrame.Shape.StyledPanel)
        self.fullscreen_tool_bar.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_9 = QHBoxLayout(self.fullscreen_tool_bar)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(5, 0, 5, 0)
        self.fullscreen_btn_run = QPushButton(self.fullscreen_tool_bar)
        self.fullscreen_btn_run.setObjectName(u"fullscreen_btn_run")
        self.fullscreen_btn_run.setMinimumSize(QSize(24, 24))
        self.fullscreen_btn_run.setMaximumSize(QSize(24, 24))
        self.fullscreen_btn_run.setStyleSheet(u"")
        self.fullscreen_btn_run.setIcon(icon7)
        self.fullscreen_btn_run.setCheckable(True)

        self.horizontalLayout_9.addWidget(self.fullscreen_btn_run)

        self.fullscreen_btn_stop = QPushButton(self.fullscreen_tool_bar)
        self.fullscreen_btn_stop.setObjectName(u"fullscreen_btn_stop")
        self.fullscreen_btn_stop.setMinimumSize(QSize(24, 24))
        self.fullscreen_btn_stop.setMaximumSize(QSize(24, 24))
        self.fullscreen_btn_stop.setIcon(icon8)
        self.fullscreen_btn_stop.setCheckable(False)
        self.fullscreen_btn_stop.setAutoExclusive(True)

        self.horizontalLayout_9.addWidget(self.fullscreen_btn_stop)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_9.addItem(self.horizontalSpacer)

        self.fullscreen_btn_unfull = QPushButton(self.fullscreen_tool_bar)
        self.fullscreen_btn_unfull.setObjectName(u"fullscreen_btn_unfull")
        self.fullscreen_btn_unfull.setMinimumSize(QSize(24, 24))
        self.fullscreen_btn_unfull.setMaximumSize(QSize(24, 24))
        icon16 = QIcon()
        icon16.addFile(u":/icons/icon--unfullscreen.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.fullscreen_btn_unfull.setIcon(icon16)
        self.fullscreen_btn_unfull.setIconSize(QSize(20, 20))
        self.fullscreen_btn_unfull.setAutoExclusive(False)

        self.horizontalLayout_9.addWidget(self.fullscreen_btn_unfull)


        self.verticalLayout_11.addWidget(self.fullscreen_tool_bar)

        self.fullscreen_view_frame = QFrame(self.central_stage_wrapper)
        self.fullscreen_view_frame.setObjectName(u"fullscreen_view_frame")
        sizePolicy11 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy11.setHorizontalStretch(0)
        sizePolicy11.setVerticalStretch(0)
        sizePolicy11.setHeightForWidth(self.fullscreen_view_frame.sizePolicy().hasHeightForWidth())
        self.fullscreen_view_frame.setSizePolicy(sizePolicy11)
        self.fullscreen_view_frame.setMinimumSize(QSize(0, 0))
        self.fullscreen_view_frame.setStyleSheet(u"")
        self.fullscreen_view_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.fullscreen_view_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_7 = QVBoxLayout(self.fullscreen_view_frame)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)

        self.verticalLayout_11.addWidget(self.fullscreen_view_frame)

        self.verticalLayout_11.setStretch(1, 1)

        self.horizontalLayout_10.addWidget(self.central_stage_wrapper, 0, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignTop)

        self.horizontalSpacer_5 = QSpacerItem(40, 0, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_10.addItem(self.horizontalSpacer_5)

        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 4)
        self.horizontalLayout_10.setStretch(2, 1)

        self.verticalLayout_8.addWidget(self.bg_layout)

        self.change_page.addWidget(self.fullscreen)

        self.verticalLayout_4.addWidget(self.change_page)


        self.retranslateUi(Form)

        self.change_page.setCurrentIndex(0)
        self.editor_stacked.setCurrentIndex(0)
        self.btn_outline_sprite.setDefault(False)
        self.btn_outline_sound.setDefault(False)
        self.btn_outline_code.setDefault(False)
        self.outline_stracked.setCurrentIndex(3)
        self.code_stacked.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.btn_logo.setText("")
        self.btn_file.setText(QCoreApplication.translate("Form", u"\u6587\u4ef6", None))
        self.btn_code_editor.setText(QCoreApplication.translate("Form", u"\u4ee3\u7801", None))
        self.btn_sprite_editor.setText(QCoreApplication.translate("Form", u"\u89d2\u8272", None))
        self.btn_setting.setText(QCoreApplication.translate("Form", u"\u5730\u56fe", None))
        self.btn_save.setText(QCoreApplication.translate("Form", u"\u58f0\u97f3", None))
        self.btn_help.setText("")
        self.btn_run.setText("")
        self.btn_stop.setText("")
        self.btn_full_screen.setText("")
        self.btn_outline_sprite.setText(QCoreApplication.translate("Form", u"\u89d2\u8272", None))
        self.btn_outline_bg.setText(QCoreApplication.translate("Form", u"\u573a\u666f", None))
        self.btn_outline_sound.setText(QCoreApplication.translate("Form", u"\u58f0\u97f3", None))
        self.btn_outline_code.setText(QCoreApplication.translate("Form", u"\u4ee3\u7801", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"\u5730\u56fe\u9875\u9762", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"\u58f0\u97f3\u9875\u9762", None))
        self.btn_add_tab.setText(QCoreApplication.translate("Form", u"+", None))
        self.animate_label.setText(QCoreApplication.translate("Form", u"ANIMATION", None))
        self.animate_preview.setText("")
        self.btn_preview_prev.setText("")
        self.btn_preview_play.setText("")
        self.btn_preview_next.setText("")
        self.btn_preview_scale.setText("")
        self.btn_preview_change_bg.setText("")
        self.btn_preview_add.setText("")
        self.fullscreen_btn_run.setText("")
        self.fullscreen_btn_stop.setText("")
        self.fullscreen_btn_unfull.setText("")
    # retranslateUi

